### ISSUE TITLE
Seems that loaded image shape is : (batch_size x 3 x 64 x 32)

### ISSUE THREAD

**Issue by ltt-gddxz** [godisboy/SDGAN#1]
I got error when running：
`ValueError: Target and input must have the same number of elements. target nelement (16) != input nelement (8)`
It seems that loaded img1 and img2  shape are both (batch_size x 3 x 64 x 32) rather than (batch_size x 3 x 64 x 64)

**Comment by godisboy** [comment]
Hi, can you provide the _full error log_?
And one thing to note: the input is randomly aligned within same class.

**Comment by ltt-gddxz** [comment]
Hi, the full error log is as follows (pycharm IDE) :

![error_log](https://user-images.githubusercontent.com/10556011/34336786-06e6e0c4-e995-11e7-8c6e-d4f2436d77e0.png)


Debug info about image shape: 

![debug](https://user-images.githubusercontent.com/10556011/34336785-06b933cc-e995-11e7-8aa1-94381e27b3d7.png)

**Comment by godisboy** [comment]
Yeah, The input is a pair of images. The data has size (batch_size* 3 * 64 * 128)(randomly aligned).
![m 0d89gp_1](https://user-images.githubusercontent.com/14243507/34340845-694549be-e9c6-11e7-9f2e-16de2cf29025.png)

Maybe I can upload the database I processed. 
In this implementation, I didn't implement the original method for processing data. But it has equal effect.

**Comment by ltt-gddxz** [comment]
I see, thanks!
